global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: backend
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:8000"]

  - job_name: etl_suppliers
    static_configs:
      - targets:
          - "etl-suppliers:9101"
          - "etl-suppliers-1:9101"
          - "etl-suppliers-2:9102"
          - "etl-suppliers-3:9103"

  - job_name: etl_compare
    static_configs:
      - targets:
          - "etl-compare:9102"
          - "etl-compare-1:9104"
